# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

APP_NAME = "LifePoop"
TARGET_SCHEME = "App"
TARGET_PATH = "Projects/#{TARGET_SCHEME}/#{TARGET_SCHEME}.xcodeproj"

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    
    increment_build_number(
        xcodeproj: "#{TARGET_PATH}",
        build_number: latest_testflight_build_number + 1
    )
    
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{TARGET_SCHEME}",
      export_method: "app-store"
    )
    
    upload_to_testflight
    slack_notify_build
  end

  lane :slack_notify_build do
    version_number = get_version_number(
      xcodeproj: "#{TARGET_PATH}",
      target: "#{TARGET_SCHEME}"
    )
    build_number = latest_testflight_build_number
    
    slack(
      message: "TestFlight에 새로운 빌드가 배포되었습니다 :rocket:",
      slack_url: ENV["SLACK_URL"],
      default_payloads: [],
      payload: {
          "버전" => version_number,
          "빌드 번호" => build_number
      }
    )
  end
end